apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ckyc.fullname" . }}-secret
type: Opaque
data:
{{ (.Files.Glob "ckyc/ckyc-keys/*").AsSecrets | indent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-env
type: Opaque
data:
  fiCode: {{ .Values.digioCkyc.fiCode | b64enc }}
  keyAlias: {{ .Values.digioCkyc.keyAlias | b64enc }}
  keystorePassword: {{ .Values.digioCkyc.keystorePassword | b64enc }}
